#######
# Compiled from magicus/functions/mana/fix0.mcscript
# to .local/share/multimc/instances/1.13.1/.minecraft/saves/maggi2/datapacks/magicus/data/magicus/functions/mana/fix0.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @a[scores={manaID=2}] run bossbar set magicus:mana_player_2 players @a[scores={manaID=2}]
execute if entity @a[scores={manaID=2}] store result bossbar magicus:mana_player_2 value run scoreboard players get @a[limit=1,scores={manaID=2}] manaCount
execute if entity @a[scores={manaID=2}] store result bossbar magicus:mana_player_2 max run scoreboard players get @a[limit=1,scores={manaID=2}] manaMax
execute if entity @a[scores={manaID=3}] run bossbar set magicus:mana_player_3 players @a[scores={manaID=3}]
execute if entity @a[scores={manaID=3}] store result bossbar magicus:mana_player_3 value run scoreboard players get @a[limit=1,scores={manaID=3}] manaCount
execute if entity @a[scores={manaID=3}] store result bossbar magicus:mana_player_3 max run scoreboard players get @a[limit=1,scores={manaID=3}] manaMax
execute if entity @a[scores={manaID=4}] run bossbar set magicus:mana_player_4 players @a[scores={manaID=4}]
execute if entity @a[scores={manaID=4}] store result bossbar magicus:mana_player_4 value run scoreboard players get @a[limit=1,scores={manaID=4}] manaCount
execute if entity @a[scores={manaID=4}] store result bossbar magicus:mana_player_4 max run scoreboard players get @a[limit=1,scores={manaID=4}] manaMax
execute if entity @a[scores={manaID=5}] run bossbar set magicus:mana_player_5 players @a[scores={manaID=5}]
execute if entity @a[scores={manaID=5}] store result bossbar magicus:mana_player_5 value run scoreboard players get @a[limit=1,scores={manaID=5}] manaCount
execute if entity @a[scores={manaID=5}] store result bossbar magicus:mana_player_5 max run scoreboard players get @a[limit=1,scores={manaID=5}] manaMax
execute if entity @a[scores={manaID=6}] run bossbar set magicus:mana_player_6 players @a[scores={manaID=6}]
execute if entity @a[scores={manaID=6}] store result bossbar magicus:mana_player_6 value run scoreboard players get @a[limit=1,scores={manaID=6}] manaCount
execute if entity @a[scores={manaID=6}] store result bossbar magicus:mana_player_6 max run scoreboard players get @a[limit=1,scores={manaID=6}] manaMax
execute if entity @a[scores={manaID=7}] run bossbar set magicus:mana_player_7 players @a[scores={manaID=7}]
execute if entity @a[scores={manaID=7}] store result bossbar magicus:mana_player_7 value run scoreboard players get @a[limit=1,scores={manaID=7}] manaCount
execute if entity @a[scores={manaID=7}] store result bossbar magicus:mana_player_7 max run scoreboard players get @a[limit=1,scores={manaID=7}] manaMax
execute if entity @a[scores={manaID=8}] run bossbar set magicus:mana_player_8 players @a[scores={manaID=8}]
execute if entity @a[scores={manaID=8}] store result bossbar magicus:mana_player_8 value run scoreboard players get @a[limit=1,scores={manaID=8}] manaCount
execute if entity @a[scores={manaID=8}] store result bossbar magicus:mana_player_8 max run scoreboard players get @a[limit=1,scores={manaID=8}] manaMax
execute if entity @a[scores={manaID=9}] run bossbar set magicus:mana_player_9 players @a[scores={manaID=9}]
execute if entity @a[scores={manaID=9}] store result bossbar magicus:mana_player_9 value run scoreboard players get @a[limit=1,scores={manaID=9}] manaCount
execute if entity @a[scores={manaID=9}] store result bossbar magicus:mana_player_9 max run scoreboard players get @a[limit=1,scores={manaID=9}] manaMax
execute if entity @a[scores={manaID=10}] run bossbar set magicus:mana_player_10 players @a[scores={manaID=10}]
execute if entity @a[scores={manaID=10}] store result bossbar magicus:mana_player_10 value run scoreboard players get @a[limit=1,scores={manaID=10}] manaCount
execute if entity @a[scores={manaID=10}] store result bossbar magicus:mana_player_10 max run scoreboard players get @a[limit=1,scores={manaID=10}] manaMax
execute if entity @a[scores={manaID=11}] run bossbar set magicus:mana_player_11 players @a[scores={manaID=11}]
execute if entity @a[scores={manaID=11}] store result bossbar magicus:mana_player_11 value run scoreboard players get @a[limit=1,scores={manaID=11}] manaCount
execute if entity @a[scores={manaID=11}] store result bossbar magicus:mana_player_11 max run scoreboard players get @a[limit=1,scores={manaID=11}] manaMax
execute if entity @a[scores={manaID=12}] run bossbar set magicus:mana_player_12 players @a[scores={manaID=12}]
execute if entity @a[scores={manaID=12}] store result bossbar magicus:mana_player_12 value run scoreboard players get @a[limit=1,scores={manaID=12}] manaCount
execute if entity @a[scores={manaID=12}] store result bossbar magicus:mana_player_12 max run scoreboard players get @a[limit=1,scores={manaID=12}] manaMax
execute if entity @a[scores={manaID=13}] run bossbar set magicus:mana_player_13 players @a[scores={manaID=13}]
execute if entity @a[scores={manaID=13}] store result bossbar magicus:mana_player_13 value run scoreboard players get @a[limit=1,scores={manaID=13}] manaCount
execute if entity @a[scores={manaID=13}] store result bossbar magicus:mana_player_13 max run scoreboard players get @a[limit=1,scores={manaID=13}] manaMax
execute if entity @a[scores={manaID=14}] run bossbar set magicus:mana_player_14 players @a[scores={manaID=14}]
execute if entity @a[scores={manaID=14}] store result bossbar magicus:mana_player_14 value run scoreboard players get @a[limit=1,scores={manaID=14}] manaCount
execute if entity @a[scores={manaID=14}] store result bossbar magicus:mana_player_14 max run scoreboard players get @a[limit=1,scores={manaID=14}] manaMax
execute if entity @a[scores={manaID=15}] run bossbar set magicus:mana_player_15 players @a[scores={manaID=15}]
execute if entity @a[scores={manaID=15}] store result bossbar magicus:mana_player_15 value run scoreboard players get @a[limit=1,scores={manaID=15}] manaCount
execute if entity @a[scores={manaID=15}] store result bossbar magicus:mana_player_15 max run scoreboard players get @a[limit=1,scores={manaID=15}] manaMax
execute if entity @a[scores={manaID=16}] run bossbar set magicus:mana_player_16 players @a[scores={manaID=16}]
execute if entity @a[scores={manaID=16}] store result bossbar magicus:mana_player_16 value run scoreboard players get @a[limit=1,scores={manaID=16}] manaCount
execute if entity @a[scores={manaID=16}] store result bossbar magicus:mana_player_16 max run scoreboard players get @a[limit=1,scores={manaID=16}] manaMax
execute if entity @a[scores={manaID=17}] run bossbar set magicus:mana_player_17 players @a[scores={manaID=17}]
execute if entity @a[scores={manaID=17}] store result bossbar magicus:mana_player_17 value run scoreboard players get @a[limit=1,scores={manaID=17}] manaCount
execute if entity @a[scores={manaID=17}] store result bossbar magicus:mana_player_17 max run scoreboard players get @a[limit=1,scores={manaID=17}] manaMax
execute if entity @a[scores={manaID=18}] run bossbar set magicus:mana_player_18 players @a[scores={manaID=18}]
execute if entity @a[scores={manaID=18}] store result bossbar magicus:mana_player_18 value run scoreboard players get @a[limit=1,scores={manaID=18}] manaCount
execute if entity @a[scores={manaID=18}] store result bossbar magicus:mana_player_18 max run scoreboard players get @a[limit=1,scores={manaID=18}] manaMax
execute if entity @a[scores={manaID=19}] run bossbar set magicus:mana_player_19 players @a[scores={manaID=19}]
execute if entity @a[scores={manaID=19}] store result bossbar magicus:mana_player_19 value run scoreboard players get @a[limit=1,scores={manaID=19}] manaCount
execute if entity @a[scores={manaID=19}] store result bossbar magicus:mana_player_19 max run scoreboard players get @a[limit=1,scores={manaID=19}] manaMax
execute if entity @a[scores={manaID=20}] run bossbar set magicus:mana_player_20 players @a[scores={manaID=20}]
execute if entity @a[scores={manaID=20}] store result bossbar magicus:mana_player_20 value run scoreboard players get @a[limit=1,scores={manaID=20}] manaCount
execute if entity @a[scores={manaID=20}] store result bossbar magicus:mana_player_20 max run scoreboard players get @a[limit=1,scores={manaID=20}] manaMax
execute if entity @a[scores={manaID=21}] run bossbar set magicus:mana_player_21 players @a[scores={manaID=21}]
execute if entity @a[scores={manaID=21}] store result bossbar magicus:mana_player_21 value run scoreboard players get @a[limit=1,scores={manaID=21}] manaCount
execute if entity @a[scores={manaID=21}] store result bossbar magicus:mana_player_21 max run scoreboard players get @a[limit=1,scores={manaID=21}] manaMax
execute if entity @a[scores={manaID=22}] run bossbar set magicus:mana_player_22 players @a[scores={manaID=22}]
execute if entity @a[scores={manaID=22}] store result bossbar magicus:mana_player_22 value run scoreboard players get @a[limit=1,scores={manaID=22}] manaCount
execute if entity @a[scores={manaID=22}] store result bossbar magicus:mana_player_22 max run scoreboard players get @a[limit=1,scores={manaID=22}] manaMax
execute if entity @a[scores={manaID=23}] run bossbar set magicus:mana_player_23 players @a[scores={manaID=23}]
execute if entity @a[scores={manaID=23}] store result bossbar magicus:mana_player_23 value run scoreboard players get @a[limit=1,scores={manaID=23}] manaCount
execute if entity @a[scores={manaID=23}] store result bossbar magicus:mana_player_23 max run scoreboard players get @a[limit=1,scores={manaID=23}] manaMax
execute if entity @a[scores={manaID=24}] run bossbar set magicus:mana_player_24 players @a[scores={manaID=24}]
execute if entity @a[scores={manaID=24}] store result bossbar magicus:mana_player_24 value run scoreboard players get @a[limit=1,scores={manaID=24}] manaCount
execute if entity @a[scores={manaID=24}] store result bossbar magicus:mana_player_24 max run scoreboard players get @a[limit=1,scores={manaID=24}] manaMax
execute if entity @a[scores={manaID=25}] run bossbar set magicus:mana_player_25 players @a[scores={manaID=25}]
execute if entity @a[scores={manaID=25}] store result bossbar magicus:mana_player_25 value run scoreboard players get @a[limit=1,scores={manaID=25}] manaCount
execute if entity @a[scores={manaID=25}] store result bossbar magicus:mana_player_25 max run scoreboard players get @a[limit=1,scores={manaID=25}] manaMax
execute if entity @a[scores={manaID=26}] run bossbar set magicus:mana_player_26 players @a[scores={manaID=26}]
execute if entity @a[scores={manaID=26}] store result bossbar magicus:mana_player_26 value run scoreboard players get @a[limit=1,scores={manaID=26}] manaCount
execute if entity @a[scores={manaID=26}] store result bossbar magicus:mana_player_26 max run scoreboard players get @a[limit=1,scores={manaID=26}] manaMax
execute if entity @a[scores={manaID=27}] run bossbar set magicus:mana_player_27 players @a[scores={manaID=27}]
execute if entity @a[scores={manaID=27}] store result bossbar magicus:mana_player_27 value run scoreboard players get @a[limit=1,scores={manaID=27}] manaCount
execute if entity @a[scores={manaID=27}] store result bossbar magicus:mana_player_27 max run scoreboard players get @a[limit=1,scores={manaID=27}] manaMax
execute if entity @a[scores={manaID=28}] run bossbar set magicus:mana_player_28 players @a[scores={manaID=28}]
execute if entity @a[scores={manaID=28}] store result bossbar magicus:mana_player_28 value run scoreboard players get @a[limit=1,scores={manaID=28}] manaCount
execute if entity @a[scores={manaID=28}] store result bossbar magicus:mana_player_28 max run scoreboard players get @a[limit=1,scores={manaID=28}] manaMax
execute if entity @a[scores={manaID=29}] run bossbar set magicus:mana_player_29 players @a[scores={manaID=29}]
execute if entity @a[scores={manaID=29}] store result bossbar magicus:mana_player_29 value run scoreboard players get @a[limit=1,scores={manaID=29}] manaCount
execute if entity @a[scores={manaID=29}] store result bossbar magicus:mana_player_29 max run scoreboard players get @a[limit=1,scores={manaID=29}] manaMax
execute if entity @a[scores={manaID=30}] run bossbar set magicus:mana_player_30 players @a[scores={manaID=30}]
execute if entity @a[scores={manaID=30}] store result bossbar magicus:mana_player_30 value run scoreboard players get @a[limit=1,scores={manaID=30}] manaCount
execute if entity @a[scores={manaID=30}] store result bossbar magicus:mana_player_30 max run scoreboard players get @a[limit=1,scores={manaID=30}] manaMax
execute if entity @a[scores={manaID=31}] run bossbar set magicus:mana_player_31 players @a[scores={manaID=31}]
execute if entity @a[scores={manaID=31}] store result bossbar magicus:mana_player_31 value run scoreboard players get @a[limit=1,scores={manaID=31}] manaCount
execute if entity @a[scores={manaID=31}] store result bossbar magicus:mana_player_31 max run scoreboard players get @a[limit=1,scores={manaID=31}] manaMax
execute if entity @a[scores={manaID=32}] run bossbar set magicus:mana_player_32 players @a[scores={manaID=32}]
execute if entity @a[scores={manaID=32}] store result bossbar magicus:mana_player_32 value run scoreboard players get @a[limit=1,scores={manaID=32}] manaCount
execute if entity @a[scores={manaID=32}] store result bossbar magicus:mana_player_32 max run scoreboard players get @a[limit=1,scores={manaID=32}] manaMax
execute if entity @a[scores={manaID=33}] run bossbar set magicus:mana_player_33 players @a[scores={manaID=33}]
execute if entity @a[scores={manaID=33}] store result bossbar magicus:mana_player_33 value run scoreboard players get @a[limit=1,scores={manaID=33}] manaCount
execute if entity @a[scores={manaID=33}] store result bossbar magicus:mana_player_33 max run scoreboard players get @a[limit=1,scores={manaID=33}] manaMax
execute if entity @a[scores={manaID=34}] run bossbar set magicus:mana_player_34 players @a[scores={manaID=34}]
execute if entity @a[scores={manaID=34}] store result bossbar magicus:mana_player_34 value run scoreboard players get @a[limit=1,scores={manaID=34}] manaCount
execute if entity @a[scores={manaID=34}] store result bossbar magicus:mana_player_34 max run scoreboard players get @a[limit=1,scores={manaID=34}] manaMax
execute if entity @a[scores={manaID=35}] run bossbar set magicus:mana_player_35 players @a[scores={manaID=35}]
execute if entity @a[scores={manaID=35}] store result bossbar magicus:mana_player_35 value run scoreboard players get @a[limit=1,scores={manaID=35}] manaCount
execute if entity @a[scores={manaID=35}] store result bossbar magicus:mana_player_35 max run scoreboard players get @a[limit=1,scores={manaID=35}] manaMax
execute if entity @a[scores={manaID=36}] run bossbar set magicus:mana_player_36 players @a[scores={manaID=36}]
execute if entity @a[scores={manaID=36}] store result bossbar magicus:mana_player_36 value run scoreboard players get @a[limit=1,scores={manaID=36}] manaCount
execute if entity @a[scores={manaID=36}] store result bossbar magicus:mana_player_36 max run scoreboard players get @a[limit=1,scores={manaID=36}] manaMax
execute if entity @a[scores={manaID=37}] run bossbar set magicus:mana_player_37 players @a[scores={manaID=37}]
execute if entity @a[scores={manaID=37}] store result bossbar magicus:mana_player_37 value run scoreboard players get @a[limit=1,scores={manaID=37}] manaCount
execute if entity @a[scores={manaID=37}] store result bossbar magicus:mana_player_37 max run scoreboard players get @a[limit=1,scores={manaID=37}] manaMax
execute if entity @a[scores={manaID=38}] run bossbar set magicus:mana_player_38 players @a[scores={manaID=38}]
execute if entity @a[scores={manaID=38}] store result bossbar magicus:mana_player_38 value run scoreboard players get @a[limit=1,scores={manaID=38}] manaCount
execute if entity @a[scores={manaID=38}] store result bossbar magicus:mana_player_38 max run scoreboard players get @a[limit=1,scores={manaID=38}] manaMax
execute if entity @a[scores={manaID=39}] run bossbar set magicus:mana_player_39 players @a[scores={manaID=39}]
execute if entity @a[scores={manaID=39}] store result bossbar magicus:mana_player_39 value run scoreboard players get @a[limit=1,scores={manaID=39}] manaCount
execute if entity @a[scores={manaID=39}] store result bossbar magicus:mana_player_39 max run scoreboard players get @a[limit=1,scores={manaID=39}] manaMax
execute if entity @a[scores={manaID=40}] run bossbar set magicus:mana_player_40 players @a[scores={manaID=40}]
execute if entity @a[scores={manaID=40}] store result bossbar magicus:mana_player_40 value run scoreboard players get @a[limit=1,scores={manaID=40}] manaCount
execute if entity @a[scores={manaID=40}] store result bossbar magicus:mana_player_40 max run scoreboard players get @a[limit=1,scores={manaID=40}] manaMax
execute if entity @a[scores={manaID=41}] run bossbar set magicus:mana_player_41 players @a[scores={manaID=41}]
execute if entity @a[scores={manaID=41}] store result bossbar magicus:mana_player_41 value run scoreboard players get @a[limit=1,scores={manaID=41}] manaCount
execute if entity @a[scores={manaID=41}] store result bossbar magicus:mana_player_41 max run scoreboard players get @a[limit=1,scores={manaID=41}] manaMax
execute if entity @a[scores={manaID=42}] run bossbar set magicus:mana_player_42 players @a[scores={manaID=42}]
execute if entity @a[scores={manaID=42}] store result bossbar magicus:mana_player_42 value run scoreboard players get @a[limit=1,scores={manaID=42}] manaCount
execute if entity @a[scores={manaID=42}] store result bossbar magicus:mana_player_42 max run scoreboard players get @a[limit=1,scores={manaID=42}] manaMax
execute if entity @a[scores={manaID=43}] run bossbar set magicus:mana_player_43 players @a[scores={manaID=43}]
execute if entity @a[scores={manaID=43}] store result bossbar magicus:mana_player_43 value run scoreboard players get @a[limit=1,scores={manaID=43}] manaCount
execute if entity @a[scores={manaID=43}] store result bossbar magicus:mana_player_43 max run scoreboard players get @a[limit=1,scores={manaID=43}] manaMax
execute if entity @a[scores={manaID=44}] run bossbar set magicus:mana_player_44 players @a[scores={manaID=44}]
execute if entity @a[scores={manaID=44}] store result bossbar magicus:mana_player_44 value run scoreboard players get @a[limit=1,scores={manaID=44}] manaCount
execute if entity @a[scores={manaID=44}] store result bossbar magicus:mana_player_44 max run scoreboard players get @a[limit=1,scores={manaID=44}] manaMax
execute if entity @a[scores={manaID=45}] run bossbar set magicus:mana_player_45 players @a[scores={manaID=45}]
execute if entity @a[scores={manaID=45}] store result bossbar magicus:mana_player_45 value run scoreboard players get @a[limit=1,scores={manaID=45}] manaCount
execute if entity @a[scores={manaID=45}] store result bossbar magicus:mana_player_45 max run scoreboard players get @a[limit=1,scores={manaID=45}] manaMax
execute if entity @a[scores={manaID=46}] run bossbar set magicus:mana_player_46 players @a[scores={manaID=46}]
execute if entity @a[scores={manaID=46}] store result bossbar magicus:mana_player_46 value run scoreboard players get @a[limit=1,scores={manaID=46}] manaCount
execute if entity @a[scores={manaID=46}] store result bossbar magicus:mana_player_46 max run scoreboard players get @a[limit=1,scores={manaID=46}] manaMax
execute if entity @a[scores={manaID=47}] run bossbar set magicus:mana_player_47 players @a[scores={manaID=47}]
execute if entity @a[scores={manaID=47}] store result bossbar magicus:mana_player_47 value run scoreboard players get @a[limit=1,scores={manaID=47}] manaCount
execute if entity @a[scores={manaID=47}] store result bossbar magicus:mana_player_47 max run scoreboard players get @a[limit=1,scores={manaID=47}] manaMax
execute if entity @a[scores={manaID=48}] run bossbar set magicus:mana_player_48 players @a[scores={manaID=48}]
execute if entity @a[scores={manaID=48}] store result bossbar magicus:mana_player_48 value run scoreboard players get @a[limit=1,scores={manaID=48}] manaCount
execute if entity @a[scores={manaID=48}] store result bossbar magicus:mana_player_48 max run scoreboard players get @a[limit=1,scores={manaID=48}] manaMax
execute if entity @a[scores={manaID=49}] run bossbar set magicus:mana_player_49 players @a[scores={manaID=49}]
execute if entity @a[scores={manaID=49}] store result bossbar magicus:mana_player_49 value run scoreboard players get @a[limit=1,scores={manaID=49}] manaCount
execute if entity @a[scores={manaID=49}] store result bossbar magicus:mana_player_49 max run scoreboard players get @a[limit=1,scores={manaID=49}] manaMax
execute if entity @a[scores={manaID=50}] run bossbar set magicus:mana_player_50 players @a[scores={manaID=50}]
execute if entity @a[scores={manaID=50}] store result bossbar magicus:mana_player_50 value run scoreboard players get @a[limit=1,scores={manaID=50}] manaCount
execute if entity @a[scores={manaID=50}] store result bossbar magicus:mana_player_50 max run scoreboard players get @a[limit=1,scores={manaID=50}] manaMax
execute if entity @a[scores={manaID=51}] run bossbar set magicus:mana_player_51 players @a[scores={manaID=51}]
execute if entity @a[scores={manaID=51}] store result bossbar magicus:mana_player_51 value run scoreboard players get @a[limit=1,scores={manaID=51}] manaCount
execute if entity @a[scores={manaID=51}] store result bossbar magicus:mana_player_51 max run scoreboard players get @a[limit=1,scores={manaID=51}] manaMax
execute if entity @a[scores={manaID=52}] run bossbar set magicus:mana_player_52 players @a[scores={manaID=52}]
execute if entity @a[scores={manaID=52}] store result bossbar magicus:mana_player_52 value run scoreboard players get @a[limit=1,scores={manaID=52}] manaCount
execute if entity @a[scores={manaID=52}] store result bossbar magicus:mana_player_52 max run scoreboard players get @a[limit=1,scores={manaID=52}] manaMax
execute if entity @a[scores={manaID=53}] run bossbar set magicus:mana_player_53 players @a[scores={manaID=53}]
execute if entity @a[scores={manaID=53}] store result bossbar magicus:mana_player_53 value run scoreboard players get @a[limit=1,scores={manaID=53}] manaCount
execute if entity @a[scores={manaID=53}] store result bossbar magicus:mana_player_53 max run scoreboard players get @a[limit=1,scores={manaID=53}] manaMax
execute if entity @a[scores={manaID=54}] run bossbar set magicus:mana_player_54 players @a[scores={manaID=54}]
execute if entity @a[scores={manaID=54}] store result bossbar magicus:mana_player_54 value run scoreboard players get @a[limit=1,scores={manaID=54}] manaCount
execute if entity @a[scores={manaID=54}] store result bossbar magicus:mana_player_54 max run scoreboard players get @a[limit=1,scores={manaID=54}] manaMax
execute if entity @a[scores={manaID=55}] run bossbar set magicus:mana_player_55 players @a[scores={manaID=55}]
execute if entity @a[scores={manaID=55}] store result bossbar magicus:mana_player_55 value run scoreboard players get @a[limit=1,scores={manaID=55}] manaCount
execute if entity @a[scores={manaID=55}] store result bossbar magicus:mana_player_55 max run scoreboard players get @a[limit=1,scores={manaID=55}] manaMax
execute if entity @a[scores={manaID=56}] run bossbar set magicus:mana_player_56 players @a[scores={manaID=56}]
execute if entity @a[scores={manaID=56}] store result bossbar magicus:mana_player_56 value run scoreboard players get @a[limit=1,scores={manaID=56}] manaCount
execute if entity @a[scores={manaID=56}] store result bossbar magicus:mana_player_56 max run scoreboard players get @a[limit=1,scores={manaID=56}] manaMax
execute if entity @a[scores={manaID=57}] run bossbar set magicus:mana_player_57 players @a[scores={manaID=57}]
execute if entity @a[scores={manaID=57}] store result bossbar magicus:mana_player_57 value run scoreboard players get @a[limit=1,scores={manaID=57}] manaCount
execute if entity @a[scores={manaID=57}] store result bossbar magicus:mana_player_57 max run scoreboard players get @a[limit=1,scores={manaID=57}] manaMax
execute if entity @a[scores={manaID=58}] run bossbar set magicus:mana_player_58 players @a[scores={manaID=58}]
execute if entity @a[scores={manaID=58}] store result bossbar magicus:mana_player_58 value run scoreboard players get @a[limit=1,scores={manaID=58}] manaCount
execute if entity @a[scores={manaID=58}] store result bossbar magicus:mana_player_58 max run scoreboard players get @a[limit=1,scores={manaID=58}] manaMax
execute if entity @a[scores={manaID=59}] run bossbar set magicus:mana_player_59 players @a[scores={manaID=59}]
execute if entity @a[scores={manaID=59}] store result bossbar magicus:mana_player_59 value run scoreboard players get @a[limit=1,scores={manaID=59}] manaCount
execute if entity @a[scores={manaID=59}] store result bossbar magicus:mana_player_59 max run scoreboard players get @a[limit=1,scores={manaID=59}] manaMax
execute if entity @a[scores={manaID=60}] run bossbar set magicus:mana_player_60 players @a[scores={manaID=60}]
execute if entity @a[scores={manaID=60}] store result bossbar magicus:mana_player_60 value run scoreboard players get @a[limit=1,scores={manaID=60}] manaCount
execute if entity @a[scores={manaID=60}] store result bossbar magicus:mana_player_60 max run scoreboard players get @a[limit=1,scores={manaID=60}] manaMax
execute if entity @a[scores={manaID=61}] run bossbar set magicus:mana_player_61 players @a[scores={manaID=61}]
execute if entity @a[scores={manaID=61}] store result bossbar magicus:mana_player_61 value run scoreboard players get @a[limit=1,scores={manaID=61}] manaCount
execute if entity @a[scores={manaID=61}] store result bossbar magicus:mana_player_61 max run scoreboard players get @a[limit=1,scores={manaID=61}] manaMax
execute if entity @a[scores={manaID=62}] run bossbar set magicus:mana_player_62 players @a[scores={manaID=62}]
execute if entity @a[scores={manaID=62}] store result bossbar magicus:mana_player_62 value run scoreboard players get @a[limit=1,scores={manaID=62}] manaCount
execute if entity @a[scores={manaID=62}] store result bossbar magicus:mana_player_62 max run scoreboard players get @a[limit=1,scores={manaID=62}] manaMax
execute if entity @a[scores={manaID=63}] run bossbar set magicus:mana_player_63 players @a[scores={manaID=63}]
execute if entity @a[scores={manaID=63}] store result bossbar magicus:mana_player_63 value run scoreboard players get @a[limit=1,scores={manaID=63}] manaCount
execute if entity @a[scores={manaID=63}] store result bossbar magicus:mana_player_63 max run scoreboard players get @a[limit=1,scores={manaID=63}] manaMax
execute if entity @a[scores={manaID=64}] run bossbar set magicus:mana_player_64 players @a[scores={manaID=64}]
execute if entity @a[scores={manaID=64}] store result bossbar magicus:mana_player_64 value run scoreboard players get @a[limit=1,scores={manaID=64}] manaCount
execute if entity @a[scores={manaID=64}] store result bossbar magicus:mana_player_64 max run scoreboard players get @a[limit=1,scores={manaID=64}] manaMax
execute if entity @a[scores={manaID=65}] run bossbar set magicus:mana_player_65 players @a[scores={manaID=65}]
execute if entity @a[scores={manaID=65}] store result bossbar magicus:mana_player_65 value run scoreboard players get @a[limit=1,scores={manaID=65}] manaCount
execute if entity @a[scores={manaID=65}] store result bossbar magicus:mana_player_65 max run scoreboard players get @a[limit=1,scores={manaID=65}] manaMax
execute if entity @a[scores={manaID=66}] run bossbar set magicus:mana_player_66 players @a[scores={manaID=66}]
execute if entity @a[scores={manaID=66}] store result bossbar magicus:mana_player_66 value run scoreboard players get @a[limit=1,scores={manaID=66}] manaCount
execute if entity @a[scores={manaID=66}] store result bossbar magicus:mana_player_66 max run scoreboard players get @a[limit=1,scores={manaID=66}] manaMax
execute if entity @a[scores={manaID=67}] run bossbar set magicus:mana_player_67 players @a[scores={manaID=67}]
execute if entity @a[scores={manaID=67}] store result bossbar magicus:mana_player_67 value run scoreboard players get @a[limit=1,scores={manaID=67}] manaCount
execute if entity @a[scores={manaID=67}] store result bossbar magicus:mana_player_67 max run scoreboard players get @a[limit=1,scores={manaID=67}] manaMax
execute if entity @a[scores={manaID=68}] run bossbar set magicus:mana_player_68 players @a[scores={manaID=68}]
execute if entity @a[scores={manaID=68}] store result bossbar magicus:mana_player_68 value run scoreboard players get @a[limit=1,scores={manaID=68}] manaCount
execute if entity @a[scores={manaID=68}] store result bossbar magicus:mana_player_68 max run scoreboard players get @a[limit=1,scores={manaID=68}] manaMax
execute if entity @a[scores={manaID=69}] run bossbar set magicus:mana_player_69 players @a[scores={manaID=69}]
execute if entity @a[scores={manaID=69}] store result bossbar magicus:mana_player_69 value run scoreboard players get @a[limit=1,scores={manaID=69}] manaCount
execute if entity @a[scores={manaID=69}] store result bossbar magicus:mana_player_69 max run scoreboard players get @a[limit=1,scores={manaID=69}] manaMax
execute if entity @a[scores={manaID=70}] run bossbar set magicus:mana_player_70 players @a[scores={manaID=70}]
execute if entity @a[scores={manaID=70}] store result bossbar magicus:mana_player_70 value run scoreboard players get @a[limit=1,scores={manaID=70}] manaCount
execute if entity @a[scores={manaID=70}] store result bossbar magicus:mana_player_70 max run scoreboard players get @a[limit=1,scores={manaID=70}] manaMax
execute if entity @a[scores={manaID=71}] run bossbar set magicus:mana_player_71 players @a[scores={manaID=71}]
execute if entity @a[scores={manaID=71}] store result bossbar magicus:mana_player_71 value run scoreboard players get @a[limit=1,scores={manaID=71}] manaCount
execute if entity @a[scores={manaID=71}] store result bossbar magicus:mana_player_71 max run scoreboard players get @a[limit=1,scores={manaID=71}] manaMax
execute if entity @a[scores={manaID=72}] run bossbar set magicus:mana_player_72 players @a[scores={manaID=72}]
execute if entity @a[scores={manaID=72}] store result bossbar magicus:mana_player_72 value run scoreboard players get @a[limit=1,scores={manaID=72}] manaCount
execute if entity @a[scores={manaID=72}] store result bossbar magicus:mana_player_72 max run scoreboard players get @a[limit=1,scores={manaID=72}] manaMax
execute if entity @a[scores={manaID=73}] run bossbar set magicus:mana_player_73 players @a[scores={manaID=73}]
execute if entity @a[scores={manaID=73}] store result bossbar magicus:mana_player_73 value run scoreboard players get @a[limit=1,scores={manaID=73}] manaCount
execute if entity @a[scores={manaID=73}] store result bossbar magicus:mana_player_73 max run scoreboard players get @a[limit=1,scores={manaID=73}] manaMax
execute if entity @a[scores={manaID=74}] run bossbar set magicus:mana_player_74 players @a[scores={manaID=74}]
execute if entity @a[scores={manaID=74}] store result bossbar magicus:mana_player_74 value run scoreboard players get @a[limit=1,scores={manaID=74}] manaCount
execute if entity @a[scores={manaID=74}] store result bossbar magicus:mana_player_74 max run scoreboard players get @a[limit=1,scores={manaID=74}] manaMax
execute if entity @a[scores={manaID=75}] run bossbar set magicus:mana_player_75 players @a[scores={manaID=75}]
execute if entity @a[scores={manaID=75}] store result bossbar magicus:mana_player_75 value run scoreboard players get @a[limit=1,scores={manaID=75}] manaCount
execute if entity @a[scores={manaID=75}] store result bossbar magicus:mana_player_75 max run scoreboard players get @a[limit=1,scores={manaID=75}] manaMax
execute if entity @a[scores={manaID=76}] run bossbar set magicus:mana_player_76 players @a[scores={manaID=76}]
execute if entity @a[scores={manaID=76}] store result bossbar magicus:mana_player_76 value run scoreboard players get @a[limit=1,scores={manaID=76}] manaCount
execute if entity @a[scores={manaID=76}] store result bossbar magicus:mana_player_76 max run scoreboard players get @a[limit=1,scores={manaID=76}] manaMax
execute if entity @a[scores={manaID=77}] run bossbar set magicus:mana_player_77 players @a[scores={manaID=77}]
execute if entity @a[scores={manaID=77}] store result bossbar magicus:mana_player_77 value run scoreboard players get @a[limit=1,scores={manaID=77}] manaCount
execute if entity @a[scores={manaID=77}] store result bossbar magicus:mana_player_77 max run scoreboard players get @a[limit=1,scores={manaID=77}] manaMax
execute if entity @a[scores={manaID=78}] run bossbar set magicus:mana_player_78 players @a[scores={manaID=78}]
execute if entity @a[scores={manaID=78}] store result bossbar magicus:mana_player_78 value run scoreboard players get @a[limit=1,scores={manaID=78}] manaCount
execute if entity @a[scores={manaID=78}] store result bossbar magicus:mana_player_78 max run scoreboard players get @a[limit=1,scores={manaID=78}] manaMax
execute if entity @a[scores={manaID=79}] run bossbar set magicus:mana_player_79 players @a[scores={manaID=79}]
execute if entity @a[scores={manaID=79}] store result bossbar magicus:mana_player_79 value run scoreboard players get @a[limit=1,scores={manaID=79}] manaCount
execute if entity @a[scores={manaID=79}] store result bossbar magicus:mana_player_79 max run scoreboard players get @a[limit=1,scores={manaID=79}] manaMax
execute if entity @a[scores={manaID=80}] run bossbar set magicus:mana_player_80 players @a[scores={manaID=80}]
execute if entity @a[scores={manaID=80}] store result bossbar magicus:mana_player_80 value run scoreboard players get @a[limit=1,scores={manaID=80}] manaCount
execute if entity @a[scores={manaID=80}] store result bossbar magicus:mana_player_80 max run scoreboard players get @a[limit=1,scores={manaID=80}] manaMax
execute if entity @a[scores={manaID=81}] run bossbar set magicus:mana_player_81 players @a[scores={manaID=81}]
execute if entity @a[scores={manaID=81}] store result bossbar magicus:mana_player_81 value run scoreboard players get @a[limit=1,scores={manaID=81}] manaCount
execute if entity @a[scores={manaID=81}] store result bossbar magicus:mana_player_81 max run scoreboard players get @a[limit=1,scores={manaID=81}] manaMax
execute if entity @a[scores={manaID=82}] run bossbar set magicus:mana_player_82 players @a[scores={manaID=82}]
execute if entity @a[scores={manaID=82}] store result bossbar magicus:mana_player_82 value run scoreboard players get @a[limit=1,scores={manaID=82}] manaCount
execute if entity @a[scores={manaID=82}] store result bossbar magicus:mana_player_82 max run scoreboard players get @a[limit=1,scores={manaID=82}] manaMax
execute if entity @a[scores={manaID=83}] run bossbar set magicus:mana_player_83 players @a[scores={manaID=83}]
execute if entity @a[scores={manaID=83}] store result bossbar magicus:mana_player_83 value run scoreboard players get @a[limit=1,scores={manaID=83}] manaCount
execute if entity @a[scores={manaID=83}] store result bossbar magicus:mana_player_83 max run scoreboard players get @a[limit=1,scores={manaID=83}] manaMax
execute if entity @a[scores={manaID=84}] run bossbar set magicus:mana_player_84 players @a[scores={manaID=84}]
execute if entity @a[scores={manaID=84}] store result bossbar magicus:mana_player_84 value run scoreboard players get @a[limit=1,scores={manaID=84}] manaCount
execute if entity @a[scores={manaID=84}] store result bossbar magicus:mana_player_84 max run scoreboard players get @a[limit=1,scores={manaID=84}] manaMax
execute if entity @a[scores={manaID=85}] run bossbar set magicus:mana_player_85 players @a[scores={manaID=85}]
execute if entity @a[scores={manaID=85}] store result bossbar magicus:mana_player_85 value run scoreboard players get @a[limit=1,scores={manaID=85}] manaCount
execute if entity @a[scores={manaID=85}] store result bossbar magicus:mana_player_85 max run scoreboard players get @a[limit=1,scores={manaID=85}] manaMax
execute if entity @a[scores={manaID=86}] run bossbar set magicus:mana_player_86 players @a[scores={manaID=86}]
execute if entity @a[scores={manaID=86}] store result bossbar magicus:mana_player_86 value run scoreboard players get @a[limit=1,scores={manaID=86}] manaCount
execute if entity @a[scores={manaID=86}] store result bossbar magicus:mana_player_86 max run scoreboard players get @a[limit=1,scores={manaID=86}] manaMax
execute if entity @a[scores={manaID=87}] run bossbar set magicus:mana_player_87 players @a[scores={manaID=87}]
execute if entity @a[scores={manaID=87}] store result bossbar magicus:mana_player_87 value run scoreboard players get @a[limit=1,scores={manaID=87}] manaCount
execute if entity @a[scores={manaID=87}] store result bossbar magicus:mana_player_87 max run scoreboard players get @a[limit=1,scores={manaID=87}] manaMax
execute if entity @a[scores={manaID=88}] run bossbar set magicus:mana_player_88 players @a[scores={manaID=88}]
execute if entity @a[scores={manaID=88}] store result bossbar magicus:mana_player_88 value run scoreboard players get @a[limit=1,scores={manaID=88}] manaCount
execute if entity @a[scores={manaID=88}] store result bossbar magicus:mana_player_88 max run scoreboard players get @a[limit=1,scores={manaID=88}] manaMax
execute if entity @a[scores={manaID=89}] run bossbar set magicus:mana_player_89 players @a[scores={manaID=89}]
execute if entity @a[scores={manaID=89}] store result bossbar magicus:mana_player_89 value run scoreboard players get @a[limit=1,scores={manaID=89}] manaCount
execute if entity @a[scores={manaID=89}] store result bossbar magicus:mana_player_89 max run scoreboard players get @a[limit=1,scores={manaID=89}] manaMax
execute if entity @a[scores={manaID=90}] run bossbar set magicus:mana_player_90 players @a[scores={manaID=90}]
execute if entity @a[scores={manaID=90}] store result bossbar magicus:mana_player_90 value run scoreboard players get @a[limit=1,scores={manaID=90}] manaCount
execute if entity @a[scores={manaID=90}] store result bossbar magicus:mana_player_90 max run scoreboard players get @a[limit=1,scores={manaID=90}] manaMax
execute if entity @a[scores={manaID=91}] run bossbar set magicus:mana_player_91 players @a[scores={manaID=91}]
execute if entity @a[scores={manaID=91}] store result bossbar magicus:mana_player_91 value run scoreboard players get @a[limit=1,scores={manaID=91}] manaCount
execute if entity @a[scores={manaID=91}] store result bossbar magicus:mana_player_91 max run scoreboard players get @a[limit=1,scores={manaID=91}] manaMax
execute if entity @a[scores={manaID=92}] run bossbar set magicus:mana_player_92 players @a[scores={manaID=92}]
execute if entity @a[scores={manaID=92}] store result bossbar magicus:mana_player_92 value run scoreboard players get @a[limit=1,scores={manaID=92}] manaCount
execute if entity @a[scores={manaID=92}] store result bossbar magicus:mana_player_92 max run scoreboard players get @a[limit=1,scores={manaID=92}] manaMax
execute if entity @a[scores={manaID=93}] run bossbar set magicus:mana_player_93 players @a[scores={manaID=93}]
execute if entity @a[scores={manaID=93}] store result bossbar magicus:mana_player_93 value run scoreboard players get @a[limit=1,scores={manaID=93}] manaCount
execute if entity @a[scores={manaID=93}] store result bossbar magicus:mana_player_93 max run scoreboard players get @a[limit=1,scores={manaID=93}] manaMax
execute if entity @a[scores={manaID=94}] run bossbar set magicus:mana_player_94 players @a[scores={manaID=94}]
execute if entity @a[scores={manaID=94}] store result bossbar magicus:mana_player_94 value run scoreboard players get @a[limit=1,scores={manaID=94}] manaCount
execute if entity @a[scores={manaID=94}] store result bossbar magicus:mana_player_94 max run scoreboard players get @a[limit=1,scores={manaID=94}] manaMax
execute if entity @a[scores={manaID=95}] run bossbar set magicus:mana_player_95 players @a[scores={manaID=95}]
execute if entity @a[scores={manaID=95}] store result bossbar magicus:mana_player_95 value run scoreboard players get @a[limit=1,scores={manaID=95}] manaCount
execute if entity @a[scores={manaID=95}] store result bossbar magicus:mana_player_95 max run scoreboard players get @a[limit=1,scores={manaID=95}] manaMax
execute if entity @a[scores={manaID=96}] run bossbar set magicus:mana_player_96 players @a[scores={manaID=96}]
execute if entity @a[scores={manaID=96}] store result bossbar magicus:mana_player_96 value run scoreboard players get @a[limit=1,scores={manaID=96}] manaCount
execute if entity @a[scores={manaID=96}] store result bossbar magicus:mana_player_96 max run scoreboard players get @a[limit=1,scores={manaID=96}] manaMax
execute if entity @a[scores={manaID=97}] run bossbar set magicus:mana_player_97 players @a[scores={manaID=97}]
execute if entity @a[scores={manaID=97}] store result bossbar magicus:mana_player_97 value run scoreboard players get @a[limit=1,scores={manaID=97}] manaCount
execute if entity @a[scores={manaID=97}] store result bossbar magicus:mana_player_97 max run scoreboard players get @a[limit=1,scores={manaID=97}] manaMax
execute if entity @a[scores={manaID=98}] run bossbar set magicus:mana_player_98 players @a[scores={manaID=98}]
execute if entity @a[scores={manaID=98}] store result bossbar magicus:mana_player_98 value run scoreboard players get @a[limit=1,scores={manaID=98}] manaCount
execute if entity @a[scores={manaID=98}] store result bossbar magicus:mana_player_98 max run scoreboard players get @a[limit=1,scores={manaID=98}] manaMax
execute if entity @a[scores={manaID=99}] run bossbar set magicus:mana_player_99 players @a[scores={manaID=99}]
execute if entity @a[scores={manaID=99}] store result bossbar magicus:mana_player_99 value run scoreboard players get @a[limit=1,scores={manaID=99}] manaCount
execute if entity @a[scores={manaID=99}] store result bossbar magicus:mana_player_99 max run scoreboard players get @a[limit=1,scores={manaID=99}] manaMax
execute if entity @a[scores={manaID=100}] run bossbar set magicus:mana_player_100 players @a[scores={manaID=100}]
execute if entity @a[scores={manaID=100}] store result bossbar magicus:mana_player_100 value run scoreboard players get @a[limit=1,scores={manaID=100}] manaCount
execute if entity @a[scores={manaID=100}] store result bossbar magicus:mana_player_100 max run scoreboard players get @a[limit=1,scores={manaID=100}] manaMax